export const categories = [
  { value: 'vehicles', label: 'Vehicles' },
  { value: 'property-rentals', label: 'Property Rentals' },
  { value: 'apparel', label: 'Apparel' },
  { value: 'classifieds', label: 'Classifieds' },
  { value: 'electronics', label: 'Electronics' },
  { value: 'entertainment', label: 'Entertainment' },
  { value: 'family', label: 'Family' },
  { value: 'free-stuff', label: 'Free Stuff' },
  { value: 'garden-outdoor', label: 'Garden & Outdoor' },
  { value: 'hobbies', label: 'Hobbies' },
  { value: 'home-goods', label: 'Home Goods' },
  { value: 'home-improvement', label: 'Home Improvement' },
  { value: 'home-sales', label: 'Home Sales' },
  { value: 'musical-instruments', label: 'Musical Instruments' },
  { value: 'office-supplies', label: 'Office Supplies' },
  { value: 'pet-supplies', label: 'Pet Supplies' },
  { value: 'sporting-goods', label: 'Sporting Goods' },
  { value: 'toys-games', label: 'Toys & Games' },
  { value: 'buy-and-sell-groups', label: 'Buy and sell groups' },
];